[package]
name = "nes"
version = "1.0.0"
edition = "2021"

[dependencies]
bitflags = "2.9"
sdl3 = "0.14.21"
rand = "0.9.0"
bitfield = "0.19.0"
rfd = "0.15.3"
discord-rpc-client = "0.4.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"