[package]
name = "nes"
version = "1.0.0"
edition = "2021"

[dependencies]
bitflags = "2.8"
sdl3 = "0.14.1"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitfield = "0.17.0"
cpal = "0.15"
rfd = "0.15.2"