name: linux
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: fedora-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo dnf update -y
        sudo dnf install -y pkg-config alsa-lib-devel wayland-devel SDL3-devel
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
