name: linux
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Enable Debian Experimental Repo & Install SDL3
      run: |
        echo "deb http://deb.debian.org/debian experimental main" | sudo tee /etc/apt/sources.list.d/debian-experimental.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9 6ED0E7B82643E131
        sudo apt-get update
        sudo apt-get -t experimental install -y libsdl3-dev
    - name: Install other dependencies
      run: |
        sudo apt-get install -y pkg-config libasound2-dev libwayland-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
