name: macos
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew update
        brew install git make cmake ninja pkg-config sdl3
        export LIBRARY_PATH="/opt/homebrew/lib:$LIBRARY_PATH"
        brew link sdl3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
