name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
      
      - name: Install Wayland and pkg-config
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libwayland-client-dev

      - name: Set PKG_CONFIG_PATH
        run: echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build the project
        run: cargo build
