name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libwayland-dev libasound2-dev
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
