name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libwayland-dev libasound2-dev
    - name: Install SDL3 from source
      run: |
        sudo apt-get install -y cmake g++ wget
        wget https://github.com/libsdl-org/SDL/releases/download/release-3.0.0/SDL3-3.0.0.tar.gz
        tar -xvzf SDL3-3.0.0.tar.gz
        cd SDL3-3.0.0
        ./configure
        make
        sudo make install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
