name: windows
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install precompiled SDL3 libraries (Visual Studio)
      run: |
        cmd /c "curl -L 'https://github.com/libsdl-org/SDL/releases/download/release-3.2.0/SDL3-devel-3.2.0-VC.zip' -o SDL3-devel-3.2.0-VC.zip"
        cmd /c "powershell -Command 'Expand-Archive -Path SDL3-devel-3.2.0-VC.zip -DestinationPath SDL3-devel-3.2.0'"
        cmd /c "cd SDL3-devel-3.2.0\lib\x64 && copy *.lib D:\a\NES\NES\"
    - name: Build
      run: cmd /c "cargo build --verbose"
    - name: Run tests
      run: cmd /c "cargo test --verbose"
