name: windows
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install precompiled SDL3 libraries (Visual Studio)
      run: |
        Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-3.2.0/SDL3-devel-3.2.0-VC.zip" -OutFile "SDL3-devel-3.2.0-VC.zip"
        Expand-Archive -Path "SDL3-devel-3.2.0-VC.zip" -DestinationPath "SDL3-devel-3.2.0"
        $env:PATH += ";$(PWD)\SDL3-devel-3.2.0\lib\x64"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
